### ISSUE TITLE
is this better than go channel?

### ISSUE THREAD

**Issue by elvizlai** [cloudfoundry/go-diodes#21]
```go
var strChan = make(chan string, 1024)

func Set(str string) {
	select {
	case strChan <- str:
	default:
		// drop
	}
}
```

I think what go-diodes better than go-channel is it override previous, but go-channel keeps previous and drops incoming.

**Comment by jasonkeene** [comment]
Yep, if dropping newer data is what you want I would use channels. diodes prioritize newer data and drop older data. They also can never block.
