### ISSUE TITLE
Len calculation in diodes

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/go-diodes#3]
re: https://github.com/cloudfoundry/diodes/issues/2

The diodes are frequently doing this thing:

```
idx := someUint64Variable % len(buffer)
```

Very, very occasionally data will be lost if the buffer length does not divide evenly into `int64 = 18446744073709551615 `. Probably not something worth stressing about, but thought I'd mention. The amount of data lost increases as the buffer size increases.

**Comment by apoydence** [comment]
@jadekler Thanks for pointing this out. I'll look into fixing it.

**Comment by ahevenor** [comment]
We are deleting the automatically generated story for this.

**Comment by apoydence** [comment]
@jadekler 

I agree that there could be a gap when the read and write indexes overflow, however if we do some math we can demonstrate that the overflow won't happen in our lifetime (permitting a quantum computer does not adapt the diodes).

Even if we could get a computer that can write to a diode once a nanosecond, it would take 584.54 years.

We could mitigate the risk, however I think adding some docs to recommend a 2^x buffer length is recommended.
