### ISSUE TITLE
Diode `TryNext` returns unnecessary values.

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/go-diodes#5]
This API returns two values. The second is unnecessary as the first value will always be nil if the second is false:

```go
data, ok := d.TryNext()
if !ok {
	// handle failed read
}
```

vs

```go
data := d.TryNext()
if data == nil {
	// handle failed read
}
```

This conveys to the user that nil reads `(nil, true)` and failed reads with data `(data, false)` are possible.

**Comment by apoydence** [comment]
@jasonkeene I agree that for pointers the `ok` is not necessary, however I like the API for the following reasons:
1. It follows golang's map convention
1. If wrapping the diode into a typed diode (much like loggregator does) where the type is a non-pointer, then the API pattern still fits.
