### ISSUE TITLE
Not swapping with nil on reads.

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/go-diodes#9]
Currently we [swap in nil](https://github.com/cloudfoundry/go-diodes/blob/9f270fb609f2f5a2cea0df935e861deccd2170a4/one_to_one.go#L67) every time we do a read:

```golang
atomic.SwapPointer(&d.buffer[idx], nil)
```

It was discussed previously that we might want to switch this to a load:

```golang
atomic.LoadPointer(&d.buffer[idx])
```

This may give us a performance improvement at the cost of memory use. Some things we should try:

- [ ] Benchmark using `atomic.LoadPointer` to see what the performance advantages are on modern hardware.
- [ ] If there are substantial performance gains, create new diodes that trade off memory use for the performance gain.

**Comment by apoydence** [comment]
Results are for OneToOne (only diode experimented against).

##### Swap
```
go test --bench=BenchmarkOneToOne --run=asdf --benchmem
BenchmarkOneToOnePoller-8        	10000000	       126 ns/op	      72 B/op	       3 allocs/op
BenchmarkOneToOneWaiter-8        	10000000	       165 ns/op	      72 B/op	       3 allocs/op
BenchmarkOneToOnePollerDrain-8   	20000000	       103 ns/op	      64 B/op	       3 allocs/op
BenchmarkOneToOneWaiterDrain-8   	10000000	       160 ns/op	      64 B/op	       3 allocs/op
```

##### Load
```
go test --bench=BenchmarkOneToOne --run=asdf --benchmem
BenchmarkOneToOnePoller-8        	10000000	       148 ns/op	      72 B/op	       3 allocs/op
BenchmarkOneToOneWaiter-8        	10000000	       185 ns/op	      72 B/op	       3 allocs/op
BenchmarkOneToOnePollerDrain-8   	20000000	       124 ns/op	      64 B/op	       3 allocs/op
BenchmarkOneToOneWaiterDrain-8   	20000000	       160 ns/op	      64 B/op	       3 allocs/op
```

**Comment by jasonkeene** [comment]
@apoydence Thanks for doing the benchmarking. Although, the results are not very intuitive.

I will go ahead and close the issue.
